version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  api:
    image: node:latest
    container_name: api_container
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - mongodb

  front:
    image: node:latest
    container_name: front_container
    ports:
      - "8080:8000"
    networks:
      - app_network
    depends_on:
      - mongodb

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
